version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      PORT: 3000
      BASE_URL: http://localhost:3000
      SMTP_USERNAME: test@test.com
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/aqua
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
