'use strict';
const FluxConstant = require('flux-constant');


module.exports = FluxConstant.set([
    'DELETE',
    'DELETE_RESPONSE',
    'GET_DETAILS',
    'GET_DETAILS_RESPONSE',
    'GET_STATUS_OPTIONS',
    'GET_STATUS_OPTIONS_RESPONSE',
    'HIDE_DETAILS_SAVE_SUCCESS',
    'HIDE_NOTE_SAVE_SUCCESS',
    'HIDE_STATUS_SAVE_SUCCESS',
    'HIDE_USER_SAVE_SUCCESS',
    'LINK_USER',
    'LINK_USER_RESPONSE',
    'NEW_NOTE',
    'NEW_NOTE_RESPONSE',
    'NEW_STATUS',
    'NEW_STATUS_RESPONSE',
    'SAVE_DETAILS',
    'SAVE_DETAILS_RESPONSE',
    'UNLINK_USER',
    'UNLINK_USER_RESPONSE'
]);
